import{a as n,i}from"./assets/vendor-BgQWO4R4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))d(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function o(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(s){if(s.ep)return;s.ep=!0;const r=o(s);fetch(s.href,r)}})();n.defaults.baseURL="https://69f0a537c1533dbedc9d7348.mockapi.io";const u=async()=>{const{data:e}=await n.get("/todo");return e},m=async e=>{const{data:t}=await n.post("/todo",e);return t},f=async e=>{const{data:t}=await n.delete(`/todo/${e}`);return t},p=({id:e,text:t})=>`
  <li class="tasks-list-item">
  <p class="tasks-list-item-text">${t}</p>
  <button class="tasks-list-item-delete-btn js-tasks-list-item-delete-btn " type="button" data-task-id="${e}">
    <svg class="tasks-list-item-delete-btn-icon" width="24" height="24">
      <use href="../img/icons.svg#icon-trash"></use>
    </svg>
  </button>
</li>
  `,a={taskForm:document.querySelector(".js-task-form"),taskList:document.querySelector(".js-tasks-list"),taskFormSbmtBtn:document.querySelector(".js-form-sbmt-btn"),taskDeletedBtn:document.querySelector(".js-tasks-list-item-delete-btn"),loader:document.querySelector(".js-loader")},l=async()=>{try{a.taskList.innerHTML="",a.loader.classList.add("is-active");const t=(await u()).map(o=>p(o)).join("");a.taskList.innerHTML=t}catch(e){console.log(e)}finally{a.loader.classList.remove("is-active")}};l();const k=async e=>{try{e.preventDefault();const{target:t}=e,o={text:t.elements.task_text.value.trim()};if(!o.text){i.error({message:"Поле для ввода не должно быть пустым",position:"topRight"});return}a.taskFormSbmtBtn.disabled=!0,await m(o),i.success({message:"Задача созданна успешно",position:"topRight"}),t.reset(),l()}catch{i.error({message:"Произошла ошибка при создании",position:"topRight"}),console.log(err)}finally{a.taskFormSbmtBtn.disabled=!1}};a.taskForm.addEventListener("submit",k);const g=async e=>{try{const t=e.target.closest(".js-tasks-list-item-delete-btn");if(!t)return;const o=t.dataset.taskId;await f(o),i.success({message:"Задача удалена успешно",position:"topRight"}),l()}catch{i.error({message:"Произошла ошибка при удалении",position:"topRight"})}};a.taskList.addEventListener("click",g);
//# sourceMappingURL=index.js.map
