import{a as c,i as n}from"./assets/vendor-BgQWO4R4.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();c.defaults.baseURL="https://69f0a537c1533dbedc9d7348.mockapi.io";const u=()=>c.get("/todo"),m=t=>c.post("/todo",t),f=t=>c.delete(`/todo/${t}`),p=({id:t,text:s})=>`
  <li class="tasks-list-item">
  <p class="tasks-list-item-text">${s}</p>
  <button class="tasks-list-item-delete-btn js-tasks-list-item-delete-btn " type="button" data-task-id="${t}">
    <svg class="tasks-list-item-delete-btn-icon" width="24" height="24">
      <use href="../img/icons.svg#icon-trash"></use>
    </svg>
  </button>
</li>
  `,i={taskForm:document.querySelector(".js-task-form"),taskList:document.querySelector(".js-tasks-list"),taskFormSbmtBtn:document.querySelector(".js-form-sbmt-btn"),taskDeletedBtn:document.querySelector(".js-tasks-list-item-delete-btn"),loader:document.querySelector(".js-loader")},d=()=>{i.taskList.innerHTML="",i.loader.classList.add("is-active"),u().then(({data:t})=>{const s=t.map(r=>p(r)).join("");i.taskList.innerHTML=s}).catch(t=>{console.log(t)}).finally(()=>{i.loader.classList.remove("is-active")})};d();const k=t=>{t.preventDefault();const{target:s}=t,r={text:s.elements.task_text.value.trim()};if(!r.text){n.error({message:"Поле для ввода не должно быть пустым",position:"topRight"});return}i.taskFormSbmtBtn.disabled=!0,m(r).then(a=>{n.success({message:"Задача созданна успешно",position:"topRight"}),s.reset(),d()}).catch(a=>{n.error({message:"Произошла ошибка при создании",position:"topRight"}),console.log(a)}).finally(()=>{i.taskFormSbmtBtn.disabled=!1})};i.taskForm.addEventListener("submit",k);const g=t=>{const s=t.target.closest(".js-tasks-list-item-delete-btn");if(!s)return;const r=s.dataset.taskId;f(r).then(a=>{n.success({message:"Задача удалена успешно",position:"topRight"}),d()}).catch(a=>{n.error({message:"Произошла ошибка при удалении",position:"topRight"})})};i.taskList.addEventListener("click",g);
//# sourceMappingURL=index.js.map
